### ISSUE TITLE
编译hbase-sdk 失败

### ISSUE THREAD

**Issue by ZhiwenDeng-dev** [CCweixiao/hbase-manager#17]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.365 s
[INFO] Finished at: 2022-12-07T15:11:52+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hbase-sdk-core_2.1: Could not resolve dependencies for project com.github.CCweixiao:hbase-sdk-core_2.1:jar:2.0.9: Could not find artifact com.github.CCweixiao:hbase-sdk-dsl:jar:2.0.9 in aliyun (http://maven.aliyun.com/nexus/content/groups/public) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]

**Comment by ZhiwenDeng-dev** [comment]
> [INFO] ------------------------------------------------------------------------ [INFO] BUILD FAILURE [INFO] ------------------------------------------------------------------------ [INFO] Total time: 10.365 s [INFO] Finished at: 2022-12-07T15:11:52+08:00 [INFO] ------------------------------------------------------------------------ [ERROR] Failed to execute goal on project hbase-sdk-core_2.1: Could not resolve dependencies for project com.github.CCweixiao:hbase-sdk-core_2.1:jar:2.0.9: Could not find artifact com.github.CCweixiao:hbase-sdk-dsl:jar:2.0.9 in aliyun (http://maven.aliyun.com/nexus/content/groups/public) -> [Help 1] [ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch. [ERROR] Re-run Maven using the -X switch to enable full debug logging. [ERROR]

已经搞定了，感谢大佬开源

**Comment by farmer-it-1024** [comment]
@ZhiwenDeng-dev : 怎么搞定的？可以分享一下？

**Comment by CCweixiao** [comment]
> [@ZhiwenDeng-dev](https://github.com/ZhiwenDeng-dev) : 怎么搞定的？可以分享一下？

还有个项目的，hbase-sdk项目，现在叫hydraql，这个项目我这几天抽空好好完善下，争取不辜负大家支持
